apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mason-pipeline
  name: nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.nfs-server.svc.cluster.local
    path: "/exports"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: mason-pipeline
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
