kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: mason-pipeline
  name: mason-pipeline
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mason-pipeline
  name: mason-pipeline-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: mason-pipeline
  name: mason-pipeline-binding
subjects:
- kind: ServiceAccount
  name: mason-pipeline
  apiGroup: ""
roleRef:
  kind: Role
  name: mason-pipeline-pod-reader
  apiGroup: rbac.authorization.k8s.io
